[package]
name = "brod-sorter"
version = "0.1.0"
authors = ["Radek Hubner <rhubner@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.4"
walkdir = "2"